---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tproxy
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tproxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tproxy
subjects:
- kind: ServiceAccount
  name: tproxy
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tproxy
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tproxy
  labels:
    tier: node
    app: tproxy
    k8s-app: tproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tproxy
  template:
    metadata:
      labels:
        tier: node
        app: tproxy
        k8s-app: tproxy
    spec:
      containers:
      - name: app
        image: k8s.gcr.io/e2e-test-images/agnhost:2.39
        args:
          - netexec
          - --http-port=80
      initContainers:
      - name: proxy
        image: aojea/tproxy:test
        restartPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
---
